Fix error: implicit declaration of function ‘exit’ on misc-progs/mapper.c
It happens on Ubuntu 24.10 GCC 14.2 presumably due to more strict error
checking having become the default.